import assert from "node:assert/strict";
import test from "node:test";
import {
  BOARD_SIZE,
  createBoard,
  getForbiddenPoints,
  getForbiddenReason,
  getOpeningMoveViolation,
  idx,
  isWin,
  type Point,
} from "../src/rules";
import { boardFromAscii } from "../test-support/board";

function mark(marks: Record<string, Point>, name: string): Point {
  const point = marks[name];
  assert.ok(point, `Expected mark '${name}' to exist in board fixture`);
  return point;
}

test("open-four extension is legal for black (..AxxxB...)", () => {
  const { board, marks } = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .....AxxxB.....
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
  `);

  const a = mark(marks, "A");
  const b = mark(marks, "B");
  assert.equal(getForbiddenReason(board, a.x, a.y), null);
  assert.equal(getForbiddenReason(board, b.x, b.y), null);
});

test("double-four move is forbidden for black", () => {
  const { board, marks } = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .......Cxxx....
    .......x.......
    .......x.......
    .......x.......
    ...............
    ...............
    ...............
    ...............
  `);

  const c = mark(marks, "C");
  assert.equal(getForbiddenReason(board, c.x, c.y), "double-four");
});

test("overline move is forbidden for black", () => {
  const { board, marks } = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ....xxxxxA.....
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
  `);

  const a = mark(marks, "A");
  assert.equal(getForbiddenReason(board, a.x, a.y), "overline");
});

test("double-three move is forbidden for black", () => {
  const { board, marks } = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .......Cxx.....
    .......x.......
    .......x.......
    ...............
    ...............
    ...............
    ...............
    ...............
  `);

  const c = mark(marks, "C");
  assert.equal(getForbiddenReason(board, c.x, c.y), "double-three");
});

test("exact five is legal even if the move also creates another four", () => {
  const { board, marks } = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .....xxCxx.....
    .......x.......
    .......x.......
    .......x.......
    ...............
    ...............
    ...............
    ...............
  `);

  const c = mark(marks, "C");
  assert.equal(getForbiddenReason(board, c.x, c.y), null);

  const next = board.slice();
  next[idx(c.x, c.y)] = 1;
  assert.equal(isWin(next, c.x, c.y, 1), true);
});

test("first black move must be center intersection", () => {
  const board = createBoard();
  const center = Math.floor(BOARD_SIZE / 2);

  assert.equal(getOpeningMoveViolation(board, 0, 0, 1), "opening-center");
  assert.equal(getOpeningMoveViolation(board, center, center, 1), null);
  assert.equal(getOpeningMoveViolation(board, 0, 0, 2), null);

  board[idx(center, center)] = 1;
  assert.equal(getOpeningMoveViolation(board, 0, 0, 1), null);
});

test("forbidden point map includes double-four and excludes legal open-four moves", () => {
  const legal = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .....AxxxB.....
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
  `);
  const forbiddenOnLegal = getForbiddenPoints(legal.board);

  const a = mark(legal.marks, "A");
  const b = mark(legal.marks, "B");
  assert.equal(forbiddenOnLegal.some((p) => p.x === a.x && p.y === a.y), false);
  assert.equal(forbiddenOnLegal.some((p) => p.x === b.x && p.y === b.y), false);

  const illegal = boardFromAscii(`
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    .......Cxxx....
    .......x.......
    .......x.......
    .......x.......
    ...............
    ...............
    ...............
    ...............
  `);
  const forbiddenOnIllegal = getForbiddenPoints(illegal.board);
  const c = mark(illegal.marks, "C");
  assert.equal(
    forbiddenOnIllegal.some((p) => p.x === c.x && p.y === c.y && p.reason === "double-four"),
    true
  );
});
